### PR TITLE
Restructure 

### PR DESCRIPTION
**Pull request by or313**
This PR introduces the main app and remove the old StuDash_home app which was intended to be the main but was named poorly.
In addition we have added the base html template which will be the structure for any feature or new page to be added to the project.

Solves #32

### CODE REVIEW

**Comment by ifireball** [comment]
Could you clean up the Git commit history in this PR? I'm seeing things there that are probably unrelated like the addition of Black lint (That was removed later?).

Also it would be best if you could put refactoring changes and changes that actually introduce new functionality in different PRs.

**Comment by or313** [comment]
@ifireball All cleaned up now :)

**Comment by ifireball** [comment]
I'm seeing template files being added in a commit that is titled "Lint fixes" - That is a little misleading. Sine this PR contains so much in it, I am forced to constantly dive into all the code to make sure there are not additional surprises....

Generally its not a good idea to surprise the reviewers....

**Comment by or313** [comment]
You are referring to `Removing StuDash_home` not `Lint fixes` and part of that commit is to remove the old app and introduce a new template.
I guess that could have been another commit just for that, will do it like that next time.
Could we approve this PR so we can open other PRs for features?

**Comment by ifireball** [comment]
So can we just remove the old app in the commit and introduce the new template in a new PR?

Its basically brand new code and should be reviewed as such.

**Pull request closed without merging**
