### PR TITLE
Accounts app

### LINKED ISSUE #31: Authentication - Register, login, logout
Create an accounts app within the project and add the logic for user to log in, log out, register, reset password as well as profile edit.
In addition to those functions we want to implement emails for forget_password and restore username.

### PR DESCRIPTION
**Pull request by or313**
This PR include changes with an accounts app which adds the logic for user to log in, log out, register, reset password as well as profile edit and emails for forgotten password and forgotten username

Fix #31

### CODE REVIEW

**Review by lmilbaum — APPROVED** [review]
The PR is too huge PR to get into the details. I trust you know what you have done.
For future PRs, please provide smaller bits.

**Comment by ravidbro** [comment]
Please resolve the conflicts so we could merge this branch

**Comment by or313** [comment]
> Please resolve the conflicts so we could merge this branch

There are no conflicts 🤷

**Comment by ravidbro** [comment]
image

**Comment by ravidbro** [comment]
Try rebasing our branch over 'main'

**Pull request merged**
