### PR TITLE
Removing comment from render import

### PR DESCRIPTION
**Pull request by or313**
Line was commented out by mistake.

### CODE REVIEW

**Comment by ravidbro** [comment]
I think you should squash such a small change to one commit

**Comment by or313** [comment]
You can squash it when merging to the upstream no problem

**Comment by ravidbro** [comment]
I'm using the option 'Rebase and merge' for a clear tree in the upstream, so squashing during merge is not an option.
I think you should squash it before the PR but if you want I will merge it like that.
The easy way is to run on your branch 'git rebase -i HEAD~2` and change the last commit from 'pick' to 'fix'.

**Comment by or313** [comment]
I dont see a problem merging it like that actually.
Could you explain again why your against using squash and merge function? Isnt exactly the same as squashing them in the branch and then merging?

**Comment by ravidbro** [comment]
Sure, for a few reasons:
1. In a real-life scenario (when working between teams in a big company), usually the merge to the upstream will be done by a bot and not by a human, so often you don't have the privileged to choose per PR which method will be used to merge the code to the upstream (usually it configured per repo).
2. There are several methods to get code from PR to the upstream; personally, I believe that using 'Merge' or 'Squash and merge' make the log (commits history) less readable, and I prefer to use the 'Rebase and push' method.
GitHub doesn't give an option of 'Squash and Rebase.'

**Review by ravidbro — APPROVED** [review]

**Pull request merged**
