### PR TITLE
Messages model - fixing minor duplication problem

### PR DESCRIPTION
**Pull request by Gal-f**
Minor changes that prevented the project from starting.
(3 out of 4 commits on the branch were dropped and only the most recent one kept on this PR)

### CODE REVIEW

**Comment by ravidbro** [comment]
There is a conflict you need to resolve first

**Comment by Gal-f** [comment]
> There is a conflict you need to resolve first

Fixed. @ravidbro

**Comment by Omeramsc** [comment]
Can you please elaborate on what those minor issues were? It's looking okay, but I don't fully understand the changes like this. 

Also - is the change to the Pipfile required on this PR? (does it solve one of those issues?)

**Review by ravidbro — CHANGES_REQUESTED** [review]
When I read https://docs.djangoproject.com/en/3.1/ref/applications/ I see:
"New applications should avoid default_app_config"

**Comment by ravidbro** [comment]
1. You have conflicts that need to be resolved.
2. as I stated (and the documentation), you should not put 'default_app_config' in the init.

If this PR is not relevant anymore, please close it.

**Pull request closed without merging**
