### PR TITLE
Adding a CI

### LINKED ISSUE #7: Add Flake8 to Ci
In order for all the developers to be aligned with the projects lint rules we want to add Flake8 to the ci for every PR to be processed through Flake8

### PR DESCRIPTION
**Pull request by meitals91**
The essence of CI is providing rapid feedback to developers about the quality of the code they
write so they can find and resolve issues quickly.
we use the “Flake8” tool to scans our code automatically.

Also making changes to the `Pipfile`, `Pipfile.lock` file. 
fixes #7

### CODE REVIEW

**Comment by ravidbro** [comment]
The commit message is good and great that you linked the issue.
On your fork in the 'actions' tab, all the jobs failed on this file.
Can you fix it on your fork before merging to the upstream?

**Comment by meitals91** [comment]
I checked my forked repo- it  seems that it was failed in the others commit but the last one doesnt failed. It is not shown in the action tab so i think that it is ok. Am i wrong? @ravidbro

**Comment by ravidbro** [comment]
I think that you should see successful jobs as well.
you can try to merge/push it to your 'main' branch in your fork and see if it helps

**Comment by Gal-f** [comment]
> I checked my forked repo- it seems that it was failed in the others commit but the last one doesnt failed. It is not shown in the action tab so i think that it is ok. Am i wrong? @ravidbro

Makes sense, doesn't it?
image
image

**Comment by meitals91** [comment]
I found the problem and fixed it. There is a successful running on my repo you can check it. @ravidbro

**Review by ravidbro — APPROVED** [review]

**Pull request merged**
